server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    open-in-view: off


  # 1. LIQUIBASE
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true

  # 2. REDIS
  data:
    redis:
      host: localhost
      port: 6379

  # 3. KEYCLOAK
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ticket-platform
          jwk-set-uri: http://localhost:8080/realms/ticket-platform/protocol/openid-connect/certs